table ip6 kira {

    # This map contains the paths this host will forward packets along.
    # Maps Incoming PathIP -> Outgoing PathIP.
    # Packets will not be decapsulated.
    map pathidtopathid {
        type ipv6_addr : ipv6_addr
    }

    # This chain forwards all matching PathIP traffic.
    chain hookin {
        type filter hook prerouting priority raw; policy accept;
        meta nftrace set 1
        ip6 daddr fcaa::/16 ip6 daddr set ip6 daddr map @pathidtopathid
    }

    chain debug {
        type filter hook prerouting priority 0; policy accept;
        meta nftrace set 1
    }
    
}
