table ip6 kira {

    # This map contains the paths this host will forward packets along.
    # Maps Incoming PathIP -> Outgoing PathIP.
    # Packets will not be decapsulated.
    map pathidtopathid {
        type ipv6_addr : ipv6_addr
    }

    # This set contains all PathIPs for paths that end on this host.
    set localpaths {
        type ipv6_addr
    }

    # This chain matches all packets that should be forwarded.
    chain hookin {
        type filter hook prerouting priority raw; policy accept;
        meta nftrace set 1
        ip6 daddr fcaa::/16 meta l4proto != icmpv6 goto forward 
    }

    # This chain forwards all PathIP traffic as configured in the pathidtopathid map.
    chain forward {
        ip6 daddr set ip6 daddr map @pathidtopathid
    }

    # This chain masquerades outgoing PathIP packets.
    chain correctsource {
        type nat hook postrouting priority 100; policy accept;
        meta l4proto icmpv6 accept
        ip6 saddr fcaa::/16 ip6 daddr fcaa::/16 masquerade
    }

    # TODO implement forwarding to physical neighbors
    
}
