table ip6 kira {

    # TODO remove tracing and debug exclusions

    # for testing only
    set excluded {
        type ipv6_addr
    }

    # This set contains all PathIDs that end on this host.
    # All packets with matching destinations will be decapsulated.
    set localpathids {
        type ipv6_addr
    }

    # This map contains all configured outgoing paths.
    # Maps NodeID -> PathID.
    # All locally generated packets with destination NodeID will be encapsulated and sent to PathID.
    map nodeidtopathid {
        type ipv6_addr : ipv6_addr
    }

    # This map contains the paths this host will forward packets along.
    # Maps Incoming PathID -> Outgoing PathID.
    # Packets will not be decapsulated.
    map pathidtopathid {
        type ipv6_addr : ipv6_addr
    }

    # debug tracing
    chain traceout {
        type filter hook output priority 0; policy accept;
        meta nftrace set 1
    }

    # debug tracing
    chain tracepost {
        type filter hook postrouting priority 300; policy accept;
        meta nftrace set 1
    }

    # This chain matches all packets sent through the dummy encapsulation ip6gre interface.
    # It extracts the inner destination IP (NodeID) and corrects the outer destination IP accordingly.
    chain swappathid {
        type filter hook output priority 0; policy accept;
        meta nftrace set 1
        # Absolutely no clue why @ll,192,128 works, why not @th,320,128?
        ip6 daddr beef::1 ip6 saddr set @ll,192,128
        ip6 daddr set ip6 saddr map @nodeidtopathid
        ip6 daddr fcaa::/16 ip6 saddr set $local
        meta nftrace set 1
        accept
    }

    # This chain matches all imcoming packets relevant for the forwarding tier.
    # Packets are either decapsulated or simply forwarded.
    chain hookpathid {
        type filter hook prerouting priority raw; policy accept;
        ip6 daddr @excluded accept
        meta nftrace set 1
        ip6 daddr @localpathids goto decapsulate
        ip6 daddr fcaa::/16 goto forwardpathid
    }

    # This chain forwards packets to the next hop as configured in the pathidtopathid map.
    chain forwardpathid {
        ip6 daddr set ip6 daddr map @pathidtopathid
        accept
    }

    # This chain decapsulates the inner packets by setting the destination address to the
    # magic IP address of the ip6gre dummy interface.
    chain decapsulate {
        ip6 daddr set $local
        ip6 saddr set beef::1
    }

    # This chain handles forwarding NodeID packets to physical neighbors.
    chain nodeid {
        # TODO forward to physical neighbors
        accept
    }
}
