spec:
  inputs:
    release_build:
      type: boolean
      default: false
      description: "Set to true to build release artifacts"

---

.semver_release_rule:
  rules:
    # matches semver release tags "v1.2.3"
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        RUSTDOCFLAGS: "-Dwarnings" # prohibit publishing of incomplete rustdoc
      interruptible: false

.force_release_build_artifacts:
  rules:
    - if: '"$[[ inputs.release_build ]]" == "true"' # force build
      when: always

include:
  - local: '.gitlab-ci/rust.yml'

stages:
  - lint          # fast lints
  - check         # in-depth code checks
  - test          # unit-, integration, doc-tests
  - build         # build kirad binaries
  - security      # security audits (cargo-audit)
  - release       # make releases


# allow successful merger even if no pipeline jobs where created because nothing was changed
no-checks:
  image: alpine
  stage: check
  script:
    - echo "Files changed not guarded by checks."
    - exit 1
  allow_failure: true # warn of absent checks

  rules:
    - changes: !reference [.rust_paths]
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

# TODO: build and release docker containers on release


release:
  image: registry.gitlab.com/gitlab-org/cli:latest
  stage: release
  extends: .semver_release_rule
  script:
    - echo "Creating release..."
    - tar -czvf docs.tar.gz -C doc

  needs:
    - build-rustdoc
    - build-kirad-release

  artifacts:
    paths:
      - kirad-*.tar.gz
      - docs.tar.gz
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Release created from tag $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
