image: rust:latest

stages:
  - test
  - format-code
  - lint-code

test-code:
  stage: test
  script:
    - cargo build --verbose
    - cargo test --verbose

lint-code:
  stage: lint-code
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  allow_failure: true
    
format-code:
  stage: format-code
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  allow_failure: true

