image: rust:latest

stages:
  - build
  - test
  - format-code
  - lint-code

build-code:
  stage: build
  script:
    - cargo build --verbose

test-code:
  stage: test
  script:
    - cargo test

lint-code:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    
format-code:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

