[workspace]
members = ["kira-lib", "kira-r2kad", "kira-forwarding", "kirad"]
default-members = ["kirad", "kira-lib"]
resolver = "2"

# Profile which optimizes the compiled binary for performance
[profile.benchmark]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"
debug = false


[workspace.package]
authors = [
  "Moritz Hepp <morith.hepp@student.kit.edu>",
  "Julius Rüberg <julius.rueberg@student.kit.edu>",
  "Jakob Müllner <uifnz@student.kit.edu>",
  "Paul Seehofer <paul.seehofer@kit.edu>",
  "Roland Bless <roland.bless@kit.edu>",
]

homepage = "https://gitlab.kit.edu/kit/tm/telematics/kira/kira-rust"
edition = "2024"

# All dependencies are well picked and although just a few have versions 1.x
# they are considered stable enough to use in production by the Rust Community.
# Nevertheless any new dependency should be weighted for its value over
# a custom implementation.

[workspace.dependencies]
# For Time Computations in general
chrono = "0.4.38"
serde_cbor = "0.11.2"
# Conveniently derive Display
derive_more = { version = "2.1.1", features = [
  "display",
  "from",
  "error",
  "debug",
] }
# For generic hash function choice
digest = "0.10.7"
# Asynchronous abstractiosn
futures = "0.3.30"
# Hexadecimal Output formatting of NodeIDs. Non-Optional as basic functionality for a NodeID.
hex = "0.4.3"
# Logging facade supporting many concrete implementations in binaries
log = "0.4.22"
# Fetching link status using netlink protocol on Linux
netlink-packet-core = "0.8.1"
netlink-packet-route = "0.29.0"
netlink-packet-utils = "0.6.0"
netlink-proto = "0.12.0"
rtnetlink = "0.20.0"
# Random NodeId generation
rand = "0.9.2"
# Rust message pack support for serde
rmp-serde = "1.3.0"
# Abstract Serialization library for Rust (kind of standard)
serde = "1.0.210"
# Required until serde supports const generics (https://crates.io/crates/serde-big-array)
serde-big-array = "0.5.1"
serde_json = "1.0.128"
# PathID generation
sha1 = "0.10.6"
# PathID generation
sha2 = "0.10.8"
# PathID generation
sha3 = "0.10.8"
# Used to support sync and async rwlock on context
tokio = { version = "1.45.1" }
# Logging facade for application level tracing
tracing = { version = "0.1.40", features = ["attributes"] }
# Async trait helper macros (https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html)
trait-variant = "0.1.2"
