services:
  node-1:
    image: r2kad-daemon:scratch
    environment:
      RUST_LOG: "debug"
      BENCH_FILE: "/bench"
    expose:
      - "19219"
    networks:
      mynetv6-1:
        ipv6_address: "2001:db8:1::10"
    volumes:
      - r2kad-bench-volume:/bench

networks:
  mynetv6-1:
    external: true
  mynetv6-2:
    external: true
volumes:
  r2kad-bench-volume:
    external: true
