# Based on the scratch container but optimized for logging
FROM rust:latest AS chef
RUN cargo install cargo-chef
WORKDIR /kirad

ENV USER=kirad
ENV UID=10001
ENV WORKDIR=kirad

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

COPY --from=planner "/$WORKDIR/recipe.json" recipe.json
RUN cargo chef cook --target x86_64-unknown-linux-musl --recipe-path recipe.json --profile benchmark --features="bench"

COPY ./ .

RUN cargo build --target x86_64-unknown-linux-musl --profile benchmark --features="bench"
RUN strip -s /kirad/target/x86_64-unknown-linux-musl/benchmark/kirad

# Create benchmark files and copy over
RUN mkdir bench/ \
    && chown -R "${USER}:${USER}" bench/

FROM scratch

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /kirad

# Copy our build
COPY --from=builder /kirad/target/x86_64-unknown-linux-musl/benchmark/kirad ./
COPY --from=builder --chown=kirad /kirad/bench ./bench

USER kirad:kirad

ENV BENCH_PATH="/kirad/bench/"

EXPOSE 8080/tcp

VOLUME ["/kirad/bench"]

CMD ["/kirad/kirad"]
