ARG BASE_IMAGE="ubuntu:latest"

FROM rust:latest AS chef
RUN cargo install cargo-chef
WORKDIR /kirad

ARG FEATURES="api"

ENV WORKDIR=kirad

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

COPY --from=planner "/$WORKDIR/recipe.json" recipe.json
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json --no-default-features --features="$FEATURES"

COPY ./ .

RUN cargo build --target x86_64-unknown-linux-musl --release --no-default-features --features="$FEATURES"
RUN strip -s /kirad/target/x86_64-unknown-linux-musl/release/kirad

FROM $BASE_IMAGE

# NOTE: Containers used for Containernet require additional packages.
# Ensure that the following packages are listed under `ADD_PACKAGES`:
#   - net-tools
#   - iproute2
#   - iputils-ping
# https://github.com/containernet/containernet/wiki#tested-images
ARG ADD_PACKAGES="curl net-tools iproute2 iputils-ping nano tcpdump bash strace iperf"

# Install required packages:
#   - nftables: Used by native fast forwarding implementation of kirad
#   - supervisor: Process management similar to init systems (systemd)
RUN apt update && \
    apt install -y \
        nftables \
        supervisor \
        ${ADD_PACKAGES} \
    && rm -rf /var/lib/apt/lists/*

# Setup supervisord (https://docs.docker.com/engine/containers/multi-service_container/#use-a-process-manager)
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/kirad.conf /etc/supervisor/conf.d

WORKDIR /kirad

# Copy our build
COPY --from=builder /kirad/target/x86_64-unknown-linux-musl/release/kirad ./
COPY kirad/conf/nftables.conf ./

WORKDIR /

# kirad api
EXPOSE 8080/tcp 


# start supervisord
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
