[package]
name = "r2kad-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bench = ["log/release_max_level_off"]

[lib]
name = "r2kad_daemon_lib"
path = "src/lib.rs"

[[bin]]
name = "r2kad-daemon"
path = "src/main.rs"

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.8", features = ["derive", "env"] }
env_logger = "0.9.0"
futures = "0.3.25"
humantime = "2.1.0"
log = "0.4.17"
r2kad-lib = { path = "../lib", features = ["serde", "udp-tokio", "rmp-serde", "in-memory-message-channel"] }
rmp-serde = "1.1.0"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.20.1", features = ["macros", "time", "net", "rt", "signal"] }
axum = "0.6.20"
serde = "1.0.190"
reqwest = { version = "0.11.22", default-features = false, features = ["serde_json", "json", "rustls-tls"] }
bitvec = "1.0.1"
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
opentelemetry = "0.21.0"
tracing-opentelemetry = "0.22.0"
opentelemetry-otlp = { version = "0.14.0", features = ["tokio"] }
opentelemetry_sdk = {  version = "0.21.2", features = ["rt-tokio"] }
globalenv = "0.4.2" # only for evaluation, remove later


[dev-dependencies]
anyhow = "1.0.66"
async-trait = "0.1.57"
chrono = "0.4.22"
log4rs = "1.1.1"
ntest = "0.8.1"
petgraph = { version = "0.6.2", features = ["serde", "serde-1"] }
