[package]
name = "kirad"
version = "0.1.0"
edition = "2021"
description = "A kira routing daemon"
license = ""
authors = ["Karlsruhe Institute of Technology"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["api", "swagger_doc"]
bench = ["log/release_max_level_off"]
api = ["axum", "hex", "sha2", "base64", "serde", "serde_derive", "serde_json"]
swagger_doc = ["utoipa", "utoipa-swagger-ui", "api", "itertools"]

[lib]
name = "r2kad_daemon_lib"
path = "src/lib.rs"

[[bin]]
name = "kirad"
path = "src/main.rs"

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.8", features = ["derive", "env"] }
env_logger = "0.9.0"
futures = "0.3.25"
humantime = "2.1.0"
log = "0.4.17"
r2kad-lib = { path = "../lib", features = ["serde", "udp-tokio", "rmp-serde", "in-memory-message-channel"] }
rmp-serde = "1.1.0"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.20.1", features = ["macros", "time", "net", "rt", "signal"] }
# rest backend
axum = { version = "0.7.4", features = ["json"], optional = true }
serde = { version = "1.0.193", features = ["derive"], optional = true }
serde_derive = { version = "1.0.193", optional = true }
serde_json = { version = "1.0.111", optional = true }
hex = { version = "0.4.3", optional = true }
# todo support other hashing algorithms
sha2 = { version = "0.10.8", optional = true }
base64 = { version = "0.21.6", optional = true }
# swagger documentation
utoipa = { version = "4.2.0", optional = true }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"], optional = true }
itertools = { version = "0.10.5", optional = true }

[dev-dependencies]
anyhow = "1.0.66"
async-trait = "0.1.57"
chrono = "0.4.22"
log4rs = "1.1.1"
ntest = "0.8.1"
petgraph = { version = "0.6.2", features = ["serde", "serde-1"] }


[package.metadata.deb]
name = "kirad"
section = "net"
depends = "$auto, iproute2, nftables"
copyright = "Karlsruhe Institute of Technology (c) 2024. All rights reserved."
maintainer-scripts = "pkg/"
assets = [
    [ "target/release/kirad", "/usr/bin/kirad", "755", ],
    [ "data/nftables.conf", "/etc/kirad/nftables.conf", "644", ],
]
systemd-units = { enable = false } #, enable = false, start = false }

