use std::{
    cell::RefCell,
    time::{
        Duration,
        Instant,
    },
};

use crate::{
    Output,
    domain::{
        ForwardingTablesUpdate,
        UnderlayNeighborDestination,
    },
    messaging::ProtocolMessage,
    runtime::UseCaseRuntime,
    use_cases::{
        BroadcastableUseCaseEvent,
        TimerId,
        UseCaseEvent,
    },
};

#[derive(Debug, Default)]
pub struct TestingUseCaseRuntime {
    // NOTE: we *always* generate the same id
    pub timer_id: usize,
    pub current_time: RefCell<Option<Instant>>,

    timers: RefCell<usize>,

    output: RefCell<Vec<Output>>,
    broadcast: RefCell<Vec<UseCaseEvent>>,
}

impl TestingUseCaseRuntime {
    /// Returns the number of registered timers.
    ///
    /// You can fire *all* registered timers by
    /// [handling](crate::use_cases::EventHandler::handle_event)
    /// the event returned by [timer](Self::timer).
    pub fn timers(&self) -> usize {
        *self.timers.borrow()
    }

    /// [Timer event](UseCaseEvent) to fire *all* registered timers.
    ///
    /// Use the [EventHandler::handle_event](crate::use_cases::EventHandler::handle_event)
    /// of a use case to handle the event.
    pub fn timer(&self) -> UseCaseEvent {
        UseCaseEvent::Timer(self.timer_id.into())
    }

    /// Get all accumulated [Output] events generated by the use cases.
    pub fn output(&self) -> impl Iterator<Item = Output> + '_ {
        self.output
            .borrow_mut()
            .drain(..)
            .collect::<Vec<_>>()
            .into_iter()
    }

    /// Get all accumulated [BroadcastableUseCaseEvent] events generated by the use cases.
    pub fn broadcast(&self) -> impl Iterator<Item = UseCaseEvent> + '_ {
        self.broadcast
            .borrow_mut()
            .drain(..)
            .collect::<Vec<_>>()
            .into_iter()
    }

    pub fn set_current_time(&self, now: Instant) {
        self.current_time.borrow_mut().replace(now);
    }
}

impl UseCaseRuntime for TestingUseCaseRuntime {
    fn register_timer(&self, _duration: Duration) -> TimerId {
        *self.timers.borrow_mut() += 1;
        self.timer_id.into()
    }

    fn remove_timer(&self, _timer_id: TimerId) {
        // just a NOOP
    }

    fn register_periodic_timer(&self, _duration: Duration) -> TimerId {
        *self.timers.borrow_mut() += 1;
        self.timer_id.into()
    }

    fn current_time(&self) -> Instant {
        self.current_time.borrow().unwrap_or_else(Instant::now)
    }

    fn send_message_via<P: Into<ProtocolMessage>>(
        &self,
        protocol_message: P,
        destination: UnderlayNeighborDestination,
    ) {
        self.output.borrow_mut().push(Output::SendProtocolMessage(
            protocol_message.into(),
            destination,
        ));
    }

    fn update_fwd_tables<U: Into<ForwardingTablesUpdate>>(&self, update: U) {
        self.output
            .borrow_mut()
            .push(Output::UpdateForwardingTables(update.into()));
    }

    fn broadcast_event<B: Into<BroadcastableUseCaseEvent>>(&self, event: B) {
        self.broadcast.borrow_mut().push(event.into().into());
    }

    fn timer_remaining_duration(&self, timer: &TimerId) -> Option<Duration> {
        if timer == &self.timer_id.into() {
            Some(Duration::ZERO)
        } else {
            None
        }
    }
}
