use std::cell::RefCell;
use std::collections::VecDeque;
use std::time::Duration;
use std::time::Instant;

use crate::Output;
use crate::domain::UnderlayNeighborDestination;
use crate::domain::protocol_event::forwarding::ForwardingTablesUpdate;
use crate::messaging::ProtocolMessage;
use crate::runtime::UseCaseRuntime;
use crate::use_cases::BroadcastableUseCaseEvent;
use crate::use_cases::TimerId;
use crate::use_cases::UseCaseEvent;

#[derive(Debug, Default)]
pub struct TestingUseCaseRuntime {
    // NOTE: we *always* generate the same id
    timer_id: usize,
    timers: RefCell<usize>,

    output: RefCell<VecDeque<Output>>,
    broadcast: RefCell<VecDeque<UseCaseEvent>>,
}

impl TestingUseCaseRuntime {
    /// Returns the number of registered timers.
    ///
    /// You can fire *all* registered timers by
    /// [handling](crate::use_cases::EventHandler::handle_event)
    /// the event returned by [timer](Self::timer).
    pub fn timers(&self) -> usize {
        *self.timers.borrow()
    }

    /// [Timer event](UseCaseEvent) to fire *all* registered timers.
    ///
    /// Use the [EventHandler::handle_event](crate::use_cases::EventHandler::handle_event)
    /// of a use case to handle the event.
    pub fn timer(&self) -> UseCaseEvent {
        UseCaseEvent::Timer(self.timer_id.into())
    }

    /// Get all accumulated [Output] events generated by the use cases.
    pub fn output(&self) -> impl Iterator<Item = Output> + '_ {
        self.output
            .borrow_mut()
            .drain(..)
            .collect::<Vec<_>>()
            .into_iter()
    }
}

impl UseCaseRuntime for TestingUseCaseRuntime {
    fn register_timer(&self, _duration: Duration) -> TimerId {
        *self.timers.borrow_mut() += 1;
        self.timer_id.into()
    }

    fn register_periodic_timer(&self, _duration: Duration) -> TimerId {
        *self.timers.borrow_mut() += 1;
        self.timer_id.into()
    }

    fn current_time(&self) -> Instant {
        Instant::now()
    }

    fn send_message_via<P: Into<ProtocolMessage>>(
        &self,
        protocol_message: P,
        destination: UnderlayNeighborDestination,
    ) {
        self.output
            .borrow_mut()
            .push_back(Output::SendProtocolMessage(
                protocol_message.into(),
                destination,
            ));
    }

    fn update_fwd_tables<U: Into<ForwardingTablesUpdate>>(&self, update: U) {
        self.output
            .borrow_mut()
            .push_back(Output::UpdateForwardingTables(update.into()));
    }

    fn broadcast_event<B: Into<BroadcastableUseCaseEvent>>(&self, event: B) {
        self.broadcast.borrow_mut().push_back(event.into().into());
    }

    fn timer_remaining_duration(&self, timer: &TimerId) -> Option<Duration> {
        if timer == &self.timer_id.into() {
            Some(Duration::ZERO)
        } else {
            None
        }
    }
}
