[package]
name = "r2kad-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For Time Computations in general
chrono = "0.4.19"
# Hexadecimal Output formatting of NodeIDs. Non-Optional as basic functionality for a NodeID.
hex = "0.4.3"
# Random NodeId generation
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "node_id_xor_bench"
harness = false

[[bench]]
name = "node_id_shared_prefix_bits"
harness = false
