[package]
name = "r2kad-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["hex", "rand"]
unstable-doc-cfg = []

[dependencies]
# To include feature flags in documentation
doc-cfg = "0.1.0"
# Hexadecimal Output formatting of NodeIDs. Non-Optional as basic functionality for a NodeID.
hex = { version = "0.4.3", optional = true }
rand = { version = "0.8.5", optional = true }

[package.metadata.docs.rs]
features = ["unstable-doc-cfg"]
