[package]
name = "kira-r2kad"
version = "0.1.0"
description = "A R²/KAD sans-i/o implementation"
license.workspace = true
authors.workspace = true
homepage.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["serde-big-array", "chrono/serde"]
binrw = ["dep:binrw"]
sync-wrapper = []


[dependencies]
chrono = { workspace = true }
derive_more = { workspace = true }
# FIXME: don't explicitly use tokio mpsc as calllback channels for API probes and message injections
tokio = { workspace = true, features = ["sync"] }
digest = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde-big-array = { workspace = true, optional = true }
sha1 = { workspace = true }
sha2 = { workspace = true, optional = true }
sha3 = { workspace = true, optional = true }
tracing = { workspace = true, features = ["attributes"] }
petgraph = "0.8.3"
binrw = { workspace = true, optional = true }

# Dependencies for examples, Benchmarks and Tests
[dev-dependencies]
tokio = { version = "1.53.1", features = [
  "rt",
  "time",
  "macros",
  "rt-multi-thread",
] }
tracing-subscriber = { workspace = true }
