[package]
name = "kirad"
version = "0.1.0"
description = "A kira routing daemon"
license = ""
authors.workspace = true
homepage.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rmp-serde", "udp-tokio"]
#bench = ["log/release_max_level_off"]
api = ["axum", "hex", "sha2", "base64", "serde", "serde_derive", "serde_json"]
swagger_doc = ["utoipa", "utoipa-swagger-ui", "api", "itertools"]
# default routing table bucket size: 3
small_buckets = []
udp-tokio = []
# rust message pack (de)serialization support
rmp-serde = ["dep:rmp-serde", "serde"]
# json (de)serialization support [debug]
serde_json = ["dep:serde_json", "serde"]

[lib]
name = "kirad_lib"
path = "src/lib.rs"

[[bin]]
name = "kirad"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
clap = { version = "4.5.17", features = ["derive", "env"] }
derive_more = { workspace = true }
futures = { workspace = true }
humantime = "2.1.0"
log = { workspace = true }
kira-lib = { path = "../kira-lib", features = ["serde"] }
kira-forwarding = { path = "../kira-forwarding" }
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { workspace = true, default-features = true, features = [
  "macros",
  "time",
  "net",
  "rt",
  "signal",
  "sync",
  "full",
  "tracing",
] }
netlink-packet-core = { workspace = true }
netlink-packet-route = { workspace = true }
netlink-proto = { workspace = true }
rtnetlink = { workspace = true }
# Debug tool
console-subscriber = "0.4.0"
# REST server backend
axum = { version = "0.7.5", features = ["json"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_derive = { workspace = true, optional = true }
rmp-serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
# TODO: support other hashing algorithms
sha2 = { workspace = true, optional = true }
base64 = { version = "0.22.1", optional = true }
# swagger documentation
utoipa = { version = "4.2.3", optional = true }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"], optional = true }
itertools = { version = "0.13.0", optional = true }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
trait-variant = { workspace = true }


[dev-dependencies]
anyhow = "1.0.88"
chrono = "0.4.38"
log4rs = "1.3.0"
ntest = "0.9.3"
petgraph = { version = "0.6.5", features = ["serde", "serde-1"] }

[package.metadata.deb]
name = "kirad"
section = "net"
depends = "$auto, iproute2, nftables"
copyright = "Karlsruhe Institute of Technology (c) 2024. All rights reserved."
maintainer-scripts = "../pkg/"
assets = [
  [
    "target/release/kirad",
    "/usr/local/bin/kirad",
    "755",
  ],
  [
    "conf/nftables.conf",
    "/usr/local/share/kira/nftables.conf",
    "644",
  ],
]
systemd-units = { enable = false } #, enable = false, start = false }
