FROM rust:latest AS chef
RUN cargo install cargo-chef
WORKDIR /r2kad-daemon

ENV WORKDIR=r2kad-daemon

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

COPY --from=planner "/$WORKDIR/recipe.json" recipe.json
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json

COPY ./ .

RUN cargo build --target x86_64-unknown-linux-musl --release
RUN strip -s /r2kad-daemon/target/x86_64-unknown-linux-musl/release/r2kad-daemon

FROM ubuntu:latest

RUN apt update && \
    apt upgrade -y && \
    apt install -y curl net-tools iproute2 nftables iputils-ping nano tcpdump bash strace iperf

# setup supervisord
RUN apt install -y supervisor
RUN mkdir -p /var/log/supervisor
COPY daemon/docker/supervisord.conf /etc/supervisord.conf

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /r2kad-daemon

# Copy our build
COPY --from=builder /r2kad-daemon/target/x86_64-unknown-linux-musl/release/r2kad-daemon ./
COPY daemon/docker/r2kad-daemon.conf /etc/supervisord.d/r2kad-daemon.conf
COPY daemon/docker/nftables.conf ./

#USER r2kad-daemon:r2kad-daemon

EXPOSE 8080/udp

# start supervisord
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
