[package]
name = "kira-lib"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde", "serde-big-array", "chrono/serde"]
sync-wrapper = []
in-memory-message-channel = ["tokio"]


[dependencies]
chrono = { workspace = true }
derive_more = { workspace = true }
# FIXME: don't explicitly use tokio mpsc as calllback channels for API probes and message injections
tokio = { workspace = true, features = ["sync"] }
digest = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive", "rc"] }
serde-big-array = { workspace = true, optional = true }
sha1 = { workspace = true }
sha2 = { workspace = true, optional = true }
sha3 = { workspace = true, optional = true }
tracing = { workspace = true, features = ["attributes"] }

# Dependencies for examples, Benchmarks and Tests
[dev-dependencies]
bus = "2.4.1"
criterion = "0.5.1"
env_logger = "0.11.5"
futures = "0.3.30"
rmp-serde = "1.3.0"
tokio = { version = "1.40.0", features = [
  "rt",
  "time",
  "macros",
  "rt-multi-thread",
] }
