import re
import secrets
import sys
import os

## Code generated by Gemini - no warranties...

def generate_new_node(match):
    # match.group(1) and (2) capture the original whitespace/indentation
    # match.group(3) captures the IPv6 prefix (e.g., "fc00")
    indent_node = match.group(1)
    indent_ipv6 = match.group(2)
    ipv6_prefix = match.group(3)
    
    # Generate a new secure 28-character (14-byte) random hex string
    new_id = secrets.token_hex(14)
    
    # Split the new ID into chunks of 4 characters for the IPv6 address
    chunks = [new_id[i:i+4] for i in range(0, 28, 4)]
    
    # Reconstruct the IPv6 address using the original prefix
    new_ipv6 = f"{ipv6_prefix}:{':'.join(chunks)}"
    
    # Return the formatted replacement string
    return f'{indent_node}node_id "{new_id}"\n{indent_ipv6}ipv6 "{new_ipv6}"'

def main():
    # 1. Ensure a filename was provided as an argument
    if len(sys.argv) < 2:
        print("Usage: python update_config.py <input_filename>")
        sys.exit(1)
        
    input_filename = sys.argv[1]
    
    # Check if the file actually exists
    if not os.path.isfile(input_filename):
        print(f"Error: The file '{input_filename}' does not exist.")
        sys.exit(1)

    # Generate output filename (e.g., "nodes.conf" -> "nodes_updated.conf")
    base_name, ext = os.path.splitext(input_filename)
    output_filename = f"{base_name}_updated{ext}"

    # 2. Read the existing configuration file
    with open(input_filename, 'r') as f:
        config_data = f.read()

    # 3. Regex pattern to find the node_id and ipv6 pair across multiple lines
    pattern = re.compile(
        r'([ \t]*)node_id\s+"[a-fA-F0-9]{28}"\r?\n([ \t]*)ipv6\s+"([a-fA-F0-9]{1,4}):(?:[a-fA-F0-9]{1,4}:){6}[a-fA-F0-9]{1,4}"'
    )

    # 4. Perform the dynamic replacement
    updated_config = pattern.sub(generate_new_node, config_data)

    # 5. Save the result
    with open(output_filename, 'w') as f:
        f.write(updated_config)

    print(f"Configuration successfully updated and saved to: {output_filename}")

if __name__ == "__main__":
    main()
